---

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/ticketswap_db
        username: ticketswap-dev
        password: ticketswap-dev
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQL5InnoDBDialect

...